### ISSUE TITLE
Infinite loop in toki-tabs

### ISSUE THREAD

**Issue by QiangF** [AmaiKinono/Tokimacs#1]
Backtrace:

    Debugger entered--Lisp error: (error "Lisp nesting exceeds ‘max-lisp-eval-depth’")
      (let ((bufs (buffer-list))) (setq bufs (cl-remove-if-not #'toki-tabs/buffer-group bufs)) (setq bufs (sort bufs #'toki-tabs/buffer-freq-higher-p)) (setq toki-tabs/sorted-buffer-list bufs))
      (if toki-tabs/inhibit-resort nil (let ((bufs (buffer-list))) (setq bufs (cl-remove-if-not #'toki-tabs/buffer-group bufs)) (setq bufs (sort bufs #'toki-tabs/buffer-freq-higher-p)) (setq toki-tabs/sorted-buffer-list bufs)))
      (if (and (eq current-buffer toki-tabs/last-active-buffer) (cl-every #'buffer-live-p toki-tabs/sorted-buffer-list)) nil (if toki-tabs/inhibit-resort nil (let ((bufs (buffer-list))) (setq bufs (cl-remove-if-not #'toki-tabs/buffer-group bufs)) (setq bufs (sort bufs #'toki-tabs/buffer-freq-higher-p)) (setq toki-tabs/sorted-buffer-list bufs))) (run-hooks 'toki-tabs-update-hook) (setq toki-tabs/last-active-buffer (current-buffer)))
      (let ((current-buffer (current-buffer))) (if (and (eq current-buffer toki-tabs/last-active-buffer) (cl-every #'buffer-live-p toki-tabs/sorted-buffer-list)) nil (if toki-tabs/inhibit-resort nil (let ((bufs (buffer-list))) (setq bufs (cl-remove-if-not #'toki-tabs/buffer-group bufs)) (setq bufs (sort bufs #'toki-tabs/buffer-freq-higher-p)) (setq toki-tabs/sorted-buffer-list bufs))) (run-hooks 'toki-tabs-update-hook) (setq toki-tabs/last-active-buffer (current-buffer))))
      (if (window-minibuffer-p) nil (let ((current-buffer (current-buffer))) (if (and (eq current-buffer toki-tabs/last-active-buffer) (cl-every #'buffer-live-p toki-tabs/sorted-buffer-list)) nil (if toki-tabs/inhibit-resort nil (let ((bufs (buffer-list))) (setq bufs (cl-remove-if-not #'toki-tabs/buffer-group bufs)) (setq bufs (sort bufs #'toki-tabs/buffer-freq-higher-p)) (setq toki-tabs/sorted-buffer-list bufs))) (run-hooks 'toki-tabs-update-hook) (setq toki-tabs/last-active-buffer (current-buffer)))))
      toki-tabs/update-buffer-list()
      run-hooks(buffer-list-update-hook)
      get-buffer-create(" *temp*-908323")
      generate-new-buffer(" *temp*")
      project--value-in-dir(project-vc-merge-submodules "~/.dotfiles/")
      project--vc-merge-submodules-p("~/.dotfiles/")
      project-try-vc("~/.dotfiles/")
      run-hook-with-args-until-success(project-try-vc "~/.dotfiles/")
      project--find-in-directory("~/.dotfiles/")
      project-current(nil)
      (and t (project-current nil))
      (let* ((project (and t (project-current nil)))) (if project (expand-file-name (cdr project)) nil))
      (closure (t) nil (let* ((project (and t (project-current nil)))) (if project (expand-file-name (cdr project)) nil)))()
      funcall((closure (t) nil (let* ((project (and t (project-current nil)))) (if project (expand-file-name (cdr project)) nil))))
      (setq toki-tabs/buffer-group (funcall toki-tabs-project-root-function))
      (save-current-buffer (set-buffer buffer) (setq toki-tabs/buffer-group (funcall toki-tabs-project-root-function)))
      (or (buffer-local-value 'toki-tabs/buffer-group buffer) (save-current-buffer (set-buffer buffer) (setq toki-tabs/buffer-group (funcall toki-tabs-project-root-function))))
      (setq group (or (buffer-local-value 'toki-tabs/buffer-group buffer) (save-current-buffer (set-buffer buffer) (setq toki-tabs/buffer-group (funcall toki-tabs-project-root-function)))))
      (cond ((eq (aref name 0) 32) nil) ((cl-some #'(lambda (common-name-prefix) (string-prefix-p common-name-prefix name)) '("*Backtrace" "*scratch" "*Faces" "*Messages" "*Customize")) "*Common*") ((setq group (or (buffer-local-value 'toki-tabs/buffer-group buffer) (save-current-buffer (set-buffer buffer) (setq toki-tabs/buffer-group (funcall toki-tabs-project-root-function))))) group) ((eq (aref name 0) 42) "*Common*") (t "*Others*"))
      (let* ((buffer (or buffer (current-buffer))) (name (buffer-name buffer)) group) (cond ((eq (aref name 0) 32) nil) ((cl-some #'(lambda (common-name-prefix) (string-prefix-p common-name-prefix name)) '("*Backtrace" "*scratch" "*Faces" "*Messages" "*Customize")) "*Common*") ((setq group (or (buffer-local-value 'toki-tabs/buffer-group buffer) (save-current-buffer (set-buffer buffer) (setq toki-tabs/buffer-group (funcall toki-tabs-project-root-function))))) group) ((eq (aref name 0) 42) "*Common*") (t "*Others*")))
      toki-tabs/buffer-group(#<buffer .dotfiles>)
      cl-remove(nil (#<buffer .dotfiles> #<buffer mini-modeline> #<buffer  *Minibuf-1*> #<buffer toki-tabs.el> #<buffer init-modeline.el> #<buffer *Messages*> #<buffer  *Minibuf-0*> #<buffer  *code-conversion-work*> #<buffer  *Echo Area 0*> #<buffer  *Echo Area 1*> #<buffer  *temp*> #<buffer  *temp*-10325> #<buffer  *temp*-320418> #<buffer  *temp*-767515> #<buffer  *temp*-337570> #<buffer  *temp*-126029> #<buffer  *temp*-700669> #<buffer  *temp*-748939> #<buffer  *temp*-714208> #<buffer  *temp*-999405> #<buffer  *temp*-487865> #<buffer  *temp*-698317> #<buffer  *temp*-90370> #<buffer  *temp*-106029> #<buffer  *temp*-690735> #<buffer  *temp*-503583> #<buffer  *temp*-975816> #<buffer  *temp*-858529> #<buffer  *temp*-864858> #<buffer  *temp*-685617> #<buffer  *temp*-298920> #<buffer  *temp*-4931> #<buffer  *temp*-668228> #<buffer  *temp*-222781> #<buffer  *temp*-324913> #<buffer  *temp*-229140> #<buffer  *temp*-641405> #<buffer  *temp*-337385> #<buffer  *temp*-474652> #<buffer  *temp*-44100> #<buffer  *temp*-514400> #<buffer  *temp*-199722> #<buffer  *temp*-606477> #<buffer  *temp*-97382> #<buffer  *temp*-212019> #<buffer  *temp*-687083> #<buffer  *temp*-954117> #<buffer  *temp*-212537> #<buffer  *temp*-221151> #<buffer  *temp*-333495> ...) :if-not toki-tabs/buffer-group)
      apply(cl-remove nil (#<buffer .dotfiles> #<buffer mini-modeline> #<buffer  *Minibuf-1*> #<buffer toki-tabs.el> #<buffer init-modeline.el> #<buffer *Messages*> #<buffer  *Minibuf-0*> #<buffer  *code-conversion-work*> #<buffer  *Echo Area 0*> #<buffer  *Echo Area 1*> #<buffer  *temp*> #<buffer  *temp*-10325> #<buffer  *temp*-320418> #<buffer  *temp*-767515> #<buffer  *temp*-337570> #<buffer  *temp*-126029> #<buffer  *temp*-700669> #<buffer  *temp*-748939> #<buffer  *temp*-714208> #<buffer  *temp*-999405> #<buffer  *temp*-487865> #<buffer  *temp*-698317> #<buffer  *temp*-90370> #<buffer  *temp*-106029> #<buffer  *temp*-690735> #<buffer  *temp*-503583> #<buffer  *temp*-975816> #<buffer  *temp*-858529> #<buffer  *temp*-864858> #<buffer  *temp*-685617> #<buffer  *temp*-298920> #<buffer  *temp*-4931> #<buffer  *temp*-668228> #<buffer  *temp*-222781> #<buffer  *temp*-324913> #<buffer  *temp*-229140> #<buffer  *temp*-641405> #<buffer  *temp*-337385> #<buffer  *temp*-474652> #<buffer  *temp*-44100> #<buffer  *temp*-514400> #<buffer  *temp*-199722> #<buffer  *temp*-606477> #<buffer  *temp*-97382> #<buffer  *temp*-212019> #<buffer  *temp*-687083> #<buffer  *temp*-954117> #<buffer  *temp*-212537> #<buffer  *temp*-221151> #<buffer  *temp*-333495> ...) :if-not toki-tabs/buffer-group nil)
      cl-remove-if-not(toki-tabs/buffer-group (#<buffer .dotfiles> #<buffer mini-modeline> #<buffer  *Minibuf-1*> #<buffer toki-tabs.el> #<buffer init-modeline.el> #<buffer *Messages*> #<buffer  *Minibuf-0*> #<buffer  *code-conversion-work*> #<buffer  *Echo Area 0*> #<buffer  *Echo Area 1*> #<buffer  *temp*> #<buffer  *temp*-10325> #<buffer  *temp*-320418> #<buffer  *temp*-767515> #<buffer  *temp*-337570> #<buffer  *temp*-126029> #<buffer  *temp*-700669> #<buffer  *temp*-748939> #<buffer  *temp*-714208> #<buffer  *temp*-999405> #<buffer  *temp*-487865> #<buffer  *temp*-698317> #<buffer  *temp*-90370> #<buffer  *temp*-106029> #<buffer  *temp*-690735> #<buffer  *temp*-503583> #<buffer  *temp*-975816> #<buffer  *temp*-858529> #<buffer  *temp*-864858> #<buffer  *temp*-685617> #<buffer  *temp*-298920> #<buffer  *temp*-4931> #<buffer  *temp*-668228> #<buffer  *temp*-222781> #<buffer  *temp*-324913> #<buffer  *temp*-229140> #<buffer  *temp*-641405> #<buffer  *temp*-337385> #<buffer  *temp*-474652> #<buffer  *temp*-44100> #<buffer  *temp*-514400> #<buffer  *temp*-199722> #<buffer  *temp*-606477> #<buffer  *temp*-97382> #<buffer  *temp*-212019> #<buffer  *temp*-687083> #<buffer  *temp*-954117> #<buffer  *temp*-212537> #<buffer  *temp*-221151> #<buffer  *temp*-333495> ...))
      (setq bufs (cl-remove-if-not #'toki-tabs/buffer-group bufs))
      (let ((bufs (buffer-list))) (setq bufs (cl-remove-if-not #'toki-tabs/buffer-group bufs)) (setq bufs (sort bufs #'toki-tabs/buffer-freq-higher-p)) (setq toki-tabs/sorted-buffer-list bufs))
      (if toki-tabs/inhibit-resort nil (let ((bufs (buffer-list))) (setq bufs (cl-remove-if-not #'toki-tabs/buffer-group bufs)) (setq bufs (sort bufs #'toki-tabs/buffer-freq-higher-p)) (setq toki-tabs/sorted-buffer-list bufs)))
      (if (and (eq current-buffer toki-tabs/last-active-buffer) (cl-every #'buffer-live-p toki-tabs/sorted-buffer-list)) nil (if toki-tabs/inhibit-resort nil (let ((bufs (buffer-list))) (setq bufs (cl-remove-if-not #'toki-tabs/buffer-group bufs)) (setq bufs (sort bufs #'toki-tabs/buffer-freq-higher-p)) (setq toki-tabs/sorted-buffer-list bufs))) (run-hooks 'toki-tabs-update-hook) (setq toki-tabs/last-active-buffer (current-buffer)))
      (let ((current-buffer (current-buffer))) (if (and (eq current-buffer toki-tabs/last-active-buffer) (cl-every #'buffer-live-p toki-tabs/sorted-buffer-list)) nil (if toki-tabs/inhibit-resort nil (let ((bufs (buffer-list))) (setq bufs (cl-remove-if-not #'toki-tabs/buffer-group bufs)) (setq bufs (sort bufs #'toki-tabs/buffer-freq-higher-p)) (setq toki-tabs/sorted-buffer-list bufs))) (run-hooks 'toki-tabs-update-hook) (setq toki-tabs/last-active-buffer (current-buffer))))
      (if (window-minibuffer-p) nil (let ((current-buffer (current-buffer))) (if (and (eq current-buffer toki-tabs/last-active-buffer) (cl-every #'buffer-live-p toki-tabs/sorted-buffer-list)) nil (if toki-tabs/inhibit-resort nil (let ((bufs (buffer-list))) (setq bufs (cl-remove-if-not #'toki-tabs/buffer-group bufs)) (setq bufs (sort bufs #'toki-tabs/buffer-freq-higher-p)) (setq toki-tabs/sorted-buffer-list bufs))) (run-hooks 'toki-tabs-update-hook) (setq toki-tabs/last-active-buffer (current-buffer)))))
    toki-tabs/update-buffer-list()

**Comment by QiangF** [comment]
貌似是 project-current 循环调用 buffer-list-update-hook

    (defvar toki-tabs-project-root-function
      (lambda ()
        (when-let ((buffer-list-update-hook nil)
                   (project (project-current nil)))
          (expand-file-name (cdr project))))
      "A function that returns project root for current buffer.")

**Comment by AmaiKinono** [comment]
谢谢。我直到最近才碰到您反映的问题，使用 TRAMP 访问某些文件时会出现。现在 toki-tabs 的刷新逻辑已经修改过，解决了这个问题，应该也避免了其他的性能问题。

---

Thanks. I've encountered this problem only recently, when visiting some files using TRAMP. Now the updating logic of toki-tabs is modified, which solves this problem and hopefully could prevent other performance problems.

**Comment by QiangF** [comment]
With respect to performance, post-command-hook is probably called more often than buffer-list-update-hook.
I find temporarily bind (buffer-list-update-hook nil) in the toki-tabs-project-root-function fixes the loop problem.
Let's close the issue.
Thank you!

**Comment by AmaiKinono** [comment]
> post-command-hook is probably called more often than buffer-list-update-hook.

The actual logic is: In `buffer-list-update-hook`, we record that buffer list is changed (by setting a variable); In `post-command-hook`, we check that variable, and *only when buffer list has changed before* (and some other predicate), we do the update. Then we set the variable to its original value.

The result is: some commands updates buffer list many many times, now we deal with it after it's finished. The workload is reduced.
