### ISSUE TITLE
wrong type returned

### ISSUE THREAD

**Issue by QiangF** [AmaiKinono/Tokimacs#3]
This function have been fixed to return a string:

    (defvar toki-tabs-project-root-function
      (lambda ()
        (when-let ((project (project-current nil))) (car (last project))))
      "A function that returns project root for current buffer.")

**Comment by AmaiKinono** [comment]
I think https://github.com/AmaiKinono/Tokimacs/commit/2d9876417e39cf1a29dbf14f972b7b559a81db0a fixes this.
