### ISSUE TITLE
toki-tabs-project-root-function makes emacs slow

### ISSUE THREAD

**Issue by QiangF** [AmaiKinono/Tokimacs#4]
Maybe use an async function?

**Comment by AmaiKinono** [comment]
Hi. Not sure if you are still using this config now, but it actually never causes problem for me. My guess is maybe you are using Windows, and in a git repository, `project-current` may use an external git process, which is slow.

I'm not sure if "async function" is a thing in elisp. Running with an idle timer may be close to the concept, but anyway, it will be weird to not immediately decide the group of a buffer when it's created, which decides how to show the tabs.

I would suggest you set `toki-tabs-project-root-function`to a quicker implementation, maybe from projectile (I'm not sure).
